feat(frontend) : add user and auth store
tirogen/Instagram pull request #1
Opened 2020-10-02 08:41 UTC by beesk135

2020-10-02 16:31 UTC, tirogen requested changes

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/index.ts
> +// import VuexPersistence from "vuex-persist";
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/index.ts
> +// import user from "@/store/modules/user";
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/index.ts
> +// const vuexLocal = new VuexPersistence<LoginState>({
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/index.ts
> +//   storage: window.localStorage,
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/index.ts
> +//   modules: ["login"]
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/index.ts
> +// });
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/index.ts
> +  // plugins: [vuexLocal.plugin]
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/auth.ts
> +// import { cloneDeep } from "lodash";
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/auth.ts
> +// import { baseState, baseMutations } from "../state";
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/auth.ts
> +import router from "../../router";
can we have absolute path?

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/auth.ts
> +// to get state in store
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/auth.ts
> +// this.$store.state.search.transcribeMessage;
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/auth.ts
> +// to dispatch
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/auth.ts
> +// this.$store.dispatch('search/start')
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +// import { cloneDeep } from "lodash";
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +// import { baseState, baseMutations } from "../state";
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +// import router from "../../router";
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +          // Patch /user/:id/updateProfile
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +          // TODO show error user fetching failed
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +        // Patch /user/:id/updateProfile
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +          // TODO show error updateProfile failed
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +        // TODO show error
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +// to get state in store
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +// this.$store.state.search.transcribeMessage;
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +// to dispatch
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/store/modules/user.ts
> +// this.$store.dispatch('search/start')
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/auth.ts
> +import { User } from "../types/user";
absolute path?

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/auth.ts
> +  isLogin = "isLogin",
???? why not boolean

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/auth.ts
> +  isFetchingLogin = "isFetchingLogin",
why not boolean?

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/auth.ts
> +  isLogin = "isLogin",
i may be wrong??

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/auth.ts
> +  isFetchingLogin = "isFetchingLogin",
i may be wrong??

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/user.ts
> +// export enum UserGender {
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/user.ts
> +//   Male = "male",
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/user.ts
> +//   Female = "female"
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/user.ts
> +// }
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/user.ts
> +  //   getOtherUser = "getOtherUser",
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/user.ts
> +  //   getUserById = "getUserById",
remove comment

2020-10-02 16:31 UTC, tirogen commented on frontend/instagram/src/types/user.ts
> +  //   getFetching = "getFetching"
remove comment

2020-10-03 11:42 UTC, beesk135 commented on frontend/instagram/src/store/index.ts
> +// import VuexPersistence from "vuex-persist";
ok

2020-10-03 11:49 UTC, beesk135 commented on frontend/instagram/src/types/auth.ts
> +  isLogin = "isLogin",
It's just the name of  getter parameter. It's actually return `!!state.token` that would check whether token is null or not then return. But this approach need changed in the future. I don't really know that check token would be good for checking login. I thought everytime calling this `isLogin` getter needs to verify at backend again whether this token is valid or not.

2020-10-03 11:50 UTC, beesk135 commented on frontend/instagram/src/types/auth.ts
> +  isLogin = "isLogin",
![image](https://user-images.githubusercontent.com/32613582/94990858-3fa01600-05a9-11eb-97ff-dffe14bd5855.png)

2020-10-03 11:51 UTC, beesk135 commented on frontend/instagram/src/types/auth.ts
> +import { User } from "../types/user";
hmmm? i'm not sure what your point is .

2020-10-03 12:24 UTC, merged